### ISSUE TITLE
Different assembly patch

### ISSUE THREAD

**Issue by valeandri** [Ale6prog/Homologous_hg38#1]
Hi @Ale6prog, thanks for makin it possible to use the tool in hg38!

I have a question about using a BAM aligned in GRCh38 but using a different patch or release. I have samples aligned to [this fasta](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa), which contains more contigs than the one used in the repo.

When I used the function --GenerateMaskedAlignmentAndVcf on one of these samples, tabix fails building the index for the coverage file 
.masked.sorted.remdup.bqsr.rg.cov.gz with this error:
```
[E::hts_idx_push] Unsorted positions on sequence #1: 1714656 followed by 1656877
```

Can this be due to the presence of other contigs? If yes, how can I adapt the tool to my assembly?

Thanks,
Valentina

**Comment by Ale6prog** [comment]
Hi @valeandri 
It is not due to the presence of the other contigs. It is due to one of the file “use_calling_hg38.bed” that wasn't sorted. 

The line 25 contained the unsorted position.

chr1	1637348	1639151
chr1	1639833	1643091
chr1	1714655	1715814 <-
chr1	1656876	1658085
chr1	1659528	1660683

It has been sorted now in the new file at line 34.

chr1	1706968	1710219
chr1	1711719	1715815
chr1	1714655	1715814 <-
chr1	1722210	1723417
chr1	1724843	1725994 

So your sample which did not work had an unsorted position in his coverage, so Tabix could not create the bed file. 
Could you indicate if it works.

Have nice day,
Alex6prog

**Comment by valeandri** [comment]
Thanks for the quick reply!

Unfortunately, it seems that there is still an issue, since now I get:
```
[March 13, 2024 at 12:43:41 PM CET] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 2.43 minutes.
Runtime.totalMemory()=851443712
[E::hts_idx_push] Unsorted positions on sequence #1: 13225590 followed by 13004675
```

So I solved by adding this line of code to Chameleolyser.pl:
```
system	("bedtools sort -i $WORKING_DIR/RAW/$SAMPLE_NAME/$SAMPLE_NAME.masked.sorted.remdup.bqsr.rg.cov > $WORKING_DIR/RAW/$SAMPLE_NAME/$SAMPLE_NAME.masked.sorted.remdup.bqsr.rg.sort.cov");
	
```

Regarding the presence of other contigs, do you think it might be a problem?

Valentina

**Comment by Ale6prog** [comment]
For the question of the presence of other contigs, you will need to see if your genome has the same position for his homologous region as the one present in the different files. I think that as your genome has more contigs there is a possiblity that the position of your homolgous region may be slightly shifted compared to the file.

Alex6prog

**Comment by valeandri** [comment]
Thanks!

I checked some positions and they look fine, but I will take this aspect into account.
